import { getDb } from "./client.ts"

export async function ensureCatalogSchema() {
  const db = getDb()

  await db.query(`
    CREATE TABLE IF NOT EXISTS catalog_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_site TEXT NOT NULL,
      source_type TEXT NOT NULL,
      source_url TEXT NOT NULL,
      source_id TEXT NOT NULL,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      images_json TEXT NOT NULL,
      extra_json TEXT NOT NULL,
      content_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(source_site, source_type, source_id)
    )
  `)

  return db
}
